version = 3.9.10
runner.dialect = scala36

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}

preset = defaultWithAlign
assumeStandardLibraryStripMargin = true
maxColumn = 100
indent.main = 3

indentYieldKeyword = false
trailingCommas = preserve
includeNoParensInSelectChains = false
optIn.breaksInsideChains = false

newlines {
  alwaysBeforeElseAfterCurlyIf = true
  beforeMultiline = keep
  beforeCurlyLambdaParams = multilineWithCaseOnly
  usingParamListModifierPrefer = before
  avoidForSimpleOverflow = [tooLong,punct,slc]
  avoidInResultType = true
  forceBeforeMultilineAssign = def
}

spaces {
  beforeContextBoundColon = IfMultipleBounds
  inImportCurlyBraces = true
  afterSymbolicDefs = true
}

literals {
  hexDigits = Upper
  scientific = Upper
}
